# Generated by Django 5.2.8 on 2025-11-13 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoKhau',
            fields=[
                ('mahokhau', models.CharField(db_column='mahokhau', max_length=10, primary_key=True, serialize=False)),
                ('diachi', models.CharField(db_column='diachi', max_length=30)),
                ('ngaylap', models.DateField(db_column='ngaylap', null=True)),
                ('ngaychuyendi', models.DateField(db_column='ngaychuyendi', null=True)),
                ('lydochuyendi', models.CharField(db_column='lydochuyendi', max_length=255, null=True)),
                ('dientichho', models.FloatField(db_column='dientichho', null=True)),
                ('soxemay', models.IntegerField(db_column='soxemay', null=True)),
                ('sooto', models.IntegerField(db_column='sooto', null=True)),
                ('soxedap', models.IntegerField(db_column='soxedap', null=True)),
            ],
            options={
                'db_table': 'hokhau',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DSChiPhiDongGop',
            fields=[
                ('ten_phi', models.CharField(db_column='tenphi', max_length=30, primary_key=True, serialize=False)),
                ('so_tien_goi_y', models.FloatField(db_column='sotiengoiy', default=0)),
            ],
            options={
                'db_table': 'dschiphidonggop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhiDongGop',
            fields=[
                ('ten_phi', models.CharField(db_column='tenphi', max_length=30, primary_key=True, serialize=False)),
                ('mahokhau', models.CharField(db_column='mahokhau', max_length=10, null=True)),
                ('sotien', models.FloatField(db_column='sotien', default=0)),
                ('ngay_dong_gop', models.DateTimeField(db_column='ngaydonggop')),
            ],
            options={
                'db_table': 'phidonggop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TamTru',
            fields=[
                ('socccd', models.CharField(db_column='socccd', max_length=15, primary_key=True, serialize=False)),
                ('ly_do', models.CharField(db_column='lydo', max_length=100, null=True)),
                ('tu_ngay', models.DateField(db_column='tungay')),
                ('den_ngay', models.DateField(db_column='denngay', null=True)),
            ],
            options={
                'db_table': 'tamtru',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TamVang',
            fields=[
                ('socccd', models.CharField(db_column='socccd', max_length=15, primary_key=True, serialize=False)),
                ('noi_tam_tru', models.CharField(db_column='noitamtru', max_length=500, null=True)),
                ('tu_ngay', models.DateField(db_column='tungay')),
                ('den_ngay', models.DateField(db_column='denngay', null=True)),
            ],
            options={
                'db_table': 'tamvang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(db_column='username', max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password', max_length=100)),
                ('hoten', models.CharField(db_column='hoten', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=100, unique=True)),
                ('sodt', models.CharField(db_column='sodt', max_length=20, null=True)),
                ('diachi', models.CharField(db_column='diachi', max_length=255, null=True)),
                ('tuoi', models.IntegerField(db_column='tuoi', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhanKhau',
            fields=[
                ('mahokhau', models.CharField(db_column='mahokhau', max_length=10)),
                ('socccd', models.CharField(db_column='socccd', max_length=15, primary_key=True, serialize=False)),
                ('hoten', models.CharField(db_column='hoten', max_length=50)),
                ('tuoi', models.IntegerField(db_column='tuoi', null=True)),
                ('gioitinh', models.CharField(db_column='gioitinh', max_length=10, null=True)),
                ('sodt', models.CharField(db_column='sodt', max_length=15, null=True)),
                ('quanhe', models.CharField(db_column='quanhe', max_length=20, null=True)),
                ('tamvang', models.IntegerField(db_column='tamvang', null=True)),
                ('tamtru', models.IntegerField(db_column='tamtru', null=True)),
            ],
            options={
                'db_table': 'nhankhau',
            },
        ),
        migrations.CreateModel(
            name='CapNhatSinhHoat',
            fields=[
                ('ho_khau', models.OneToOneField(db_column='mahokhau', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cnpm.hokhau')),
                ('tien_dien', models.FloatField(db_column='tiendien', default=0)),
                ('tien_nuoc', models.FloatField(db_column='tiennuoc', default=0)),
                ('tien_internet', models.FloatField(db_column='tieninternet', default=0)),
                ('ngay_cap_nhat', models.DateTimeField(db_column='ngaycapnhat')),
            ],
            options={
                'db_table': 'capnhatsinhhoat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhiDichVu',
            fields=[
                ('ho_khau', models.OneToOneField(db_column='mahokhau', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cnpm.hokhau')),
                ('nam', models.IntegerField(db_column='nam')),
                ('giaphi', models.FloatField(db_column='giaphi', default=0)),
                ('tien_nop_moi_thang', models.FloatField(db_column='tiennopmoithang', default=0)),
                ('thang1', models.FloatField(db_column='thang1', default=0)),
                ('thang2', models.FloatField(db_column='thang2', default=0)),
                ('thang3', models.FloatField(db_column='thang3', default=0)),
                ('thang4', models.FloatField(db_column='thang4', default=0)),
                ('thang5', models.FloatField(db_column='thang5', default=0)),
                ('thang6', models.FloatField(db_column='thang6', default=0)),
                ('thang7', models.FloatField(db_column='thang7', default=0)),
                ('thang8', models.FloatField(db_column='thang8', default=0)),
                ('thang9', models.FloatField(db_column='thang9', default=0)),
                ('thang10', models.FloatField(db_column='thang10', default=0)),
                ('thang11', models.FloatField(db_column='thang11', default=0)),
                ('thang12', models.FloatField(db_column='thang12', default=0)),
            ],
            options={
                'db_table': 'phidichvu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhiGuiXe',
            fields=[
                ('ho_khau', models.OneToOneField(db_column='mahokhau', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cnpm.hokhau')),
                ('gia_xemay', models.FloatField(db_column='giaxemay', default=0)),
                ('gia_oto', models.FloatField(db_column='giaoto', default=0)),
                ('gia_xedap', models.FloatField(db_column='giaxedap', default=0)),
                ('tien_nop_moi_thang', models.FloatField(db_column='tiennopmoithang', default=0)),
                ('nam', models.IntegerField(db_column='nam')),
                ('thang1', models.FloatField(db_column='thang1', default=0)),
                ('thang2', models.FloatField(db_column='thang2', default=0)),
                ('thang3', models.FloatField(db_column='thang3', default=0)),
                ('thang4', models.FloatField(db_column='thang4', default=0)),
                ('thang5', models.FloatField(db_column='thang5', default=0)),
                ('thang6', models.FloatField(db_column='thang6', default=0)),
                ('thang7', models.FloatField(db_column='thang7', default=0)),
                ('thang8', models.FloatField(db_column='thang8', default=0)),
                ('thang9', models.FloatField(db_column='thang9', default=0)),
                ('thang10', models.FloatField(db_column='thang10', default=0)),
                ('thang11', models.FloatField(db_column='thang11', default=0)),
                ('thang12', models.FloatField(db_column='thang12', default=0)),
            ],
            options={
                'db_table': 'phiguixe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhiQuanLy',
            fields=[
                ('ho_khau', models.OneToOneField(db_column='mahokhau', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cnpm.hokhau')),
                ('giaphi', models.FloatField(db_column='giaphi', default=0)),
                ('tien_nop_moi_thang', models.FloatField(db_column='tiennopmoithang', default=0)),
                ('nam', models.IntegerField(db_column='nam')),
                ('thang1', models.FloatField(db_column='thang1', default=0)),
                ('thang2', models.FloatField(db_column='thang2', default=0)),
                ('thang3', models.FloatField(db_column='thang3', default=0)),
                ('thang4', models.FloatField(db_column='thang4', default=0)),
                ('thang5', models.FloatField(db_column='thang5', default=0)),
                ('thang6', models.FloatField(db_column='thang6', default=0)),
                ('thang7', models.FloatField(db_column='thang7', default=0)),
                ('thang8', models.FloatField(db_column='thang8', default=0)),
                ('thang9', models.FloatField(db_column='thang9', default=0)),
                ('thang10', models.FloatField(db_column='thang10', default=0)),
                ('thang11', models.FloatField(db_column='thang11', default=0)),
                ('thang12', models.FloatField(db_column='thang12', default=0)),
            ],
            options={
                'db_table': 'phiquanly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhiSinhHoat',
            fields=[
                ('ho_khau', models.OneToOneField(db_column='mahokhau', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cnpm.hokhau')),
                ('nam', models.IntegerField(db_column='nam')),
                ('thang1', models.FloatField(db_column='thang1', default=0)),
                ('thang2', models.FloatField(db_column='thang2', default=0)),
                ('thang3', models.FloatField(db_column='thang3', default=0)),
                ('thang4', models.FloatField(db_column='thang4', default=0)),
                ('thang5', models.FloatField(db_column='thang5', default=0)),
                ('thang6', models.FloatField(db_column='thang6', default=0)),
                ('thang7', models.FloatField(db_column='thang7', default=0)),
                ('thang8', models.FloatField(db_column='thang8', default=0)),
                ('thang9', models.FloatField(db_column='thang9', default=0)),
                ('thang10', models.FloatField(db_column='thang10', default=0)),
                ('thang11', models.FloatField(db_column='thang11', default=0)),
                ('thang12', models.FloatField(db_column='thang12', default=0)),
            ],
            options={
                'db_table': 'phisinhhoat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('ho_khau', models.OneToOneField(db_column='mahokhau', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cnpm.hokhau')),
                ('so_tien_thanh_toan', models.FloatField(db_column='sotienthanhtoan')),
                ('ngay_thanh_toan', models.DateTimeField(db_column='ngaythanhtoan')),
            ],
            options={
                'db_table': 'thanhtoan',
                'managed': False,
            },
        ),
    ]
