@echo off
echo Starting Backend...
start "Backend Server" cmd /k "cd backend && call .venv\Scripts\activate && python manage.py runserver"

echo Starting Frontend...
start "Frontend Client" cmd /k "cd frontend && npm run dev"

echo Application launching...
