# Generated by Django 5.2.8 on 2025-11-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exemple',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'exemple',
            },
        ),
    ]
