# Generated by Django 5.2.8 on 2025-12-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiQuanLy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucPhi',
            fields=[
                ('MaLoaiPhi', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã Loại Phí')),
                ('TenLoaiPhi', models.CharField(max_length=150, verbose_name='Tên Loại Phí')),
                ('DonGia', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn Giá')),
                ('DonViTinh', models.CharField(choices=[('VND', 'Đồng (VNĐ)'), ('DO', 'Đô la Mỹ (USD)'), ('EU', 'Euro (EUR)'), ('KHAC', 'Khác')], default='VND', max_length=10, verbose_name='Đơn Vị Tính')),
                ('KyThuPhi', models.CharField(choices=[('THANG', 'Theo Tháng'), ('QUY', 'Theo Quý'), ('NAM', 'Theo Năm'), ('KHAC', 'Khác')], default='THANG', max_length=10, verbose_name='Kỳ Thu Phí')),
            ],
            options={
                'db_table': 'DanhMucPhi',
                'ordering': ['MaLoaiPhi'],
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('MaHoaDon', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã Hóa Đơn')),
                ('Thang', models.IntegerField(verbose_name='Tháng')),
                ('Nam', models.IntegerField(verbose_name='Năm')),
                ('TongTien', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng Tiền')),
                ('TrangThai', models.IntegerField(choices=[(0, 'Chưa Thanh Toán'), (1, 'Đã Thanh Toán'), (2, 'Đã Hủy')], default=0, verbose_name='Trạng Thái Thanh Toán')),
                ('NgayTao', models.DateField(auto_now_add=True, verbose_name='Ngày Tạo Hóa Đơn')),
                ('NgayThanhToan', models.DateTimeField(blank=True, null=True, verbose_name='Ngày Giờ Thanh Toán')),
                ('NguoiDongTien', models.CharField(blank=True, max_length=200, null=True, verbose_name='Người Đóng Tiền')),
                ('MaCanHo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don', to='apiQuanLy.canho', verbose_name='Mã Căn Hộ')),
            ],
            options={
                'db_table': 'HoaDon',
                'ordering': ['MaHoaDon'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('MaChiTiet', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã Chi Tiết')),
                ('SoLuong', models.IntegerField(default=1, verbose_name='Số Lượng')),
                ('ThanhTien', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Thành Tiền')),
                ('GhiChu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi Chú')),
                ('MaLoaiPhi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_hoa_don', to='apiKeToan.danhmucphi', verbose_name='Mã Loại Phí')),
                ('MaHoaDon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='apiKeToan.hoadon', verbose_name='Mã Hóa Đơn')),
            ],
            options={
                'db_table': 'ChiTietHoaDon',
                'ordering': ['MaHoaDon', 'MaLoaiPhi'],
            },
        ),
        migrations.CreateModel(
            name='PhuongTien',
            fields=[
                ('MaXe', models.AutoField(help_text='ID TỰ TĂNG (Khóa chính)', primary_key=True, serialize=False, verbose_name='Mã Xe')),
                ('BienSo', models.CharField(max_length=20, unique=True, verbose_name='Biển Số Xe')),
                ('LoaiXe', models.CharField(choices=[('XM', 'Xe Máy'), ('OTO', 'Ô Tô'), ('XD', 'Xe Đạp/Xe Điện'), ('KHAC', 'Khác')], default='KHAC', max_length=10, verbose_name='Loại Xe')),
                ('MauXe', models.CharField(blank=True, max_length=50, null=True, verbose_name='Màu Xe')),
                ('MaCanHo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='can_ho_dang_ky_phuong_tien', to='apiQuanLy.canho', verbose_name='Căn Hộ Đăng Ký')),
                ('MaCuDan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_so_huu_phuong_tien', to='apiQuanLy.cudan', verbose_name='Chủ Sở Hữu')),
            ],
            options={
                'db_table': 'PhuongTien',
                'ordering': ['MaXe'],
            },
        ),
        migrations.CreateModel(
            name='ChiSoDienNuoc',
            fields=[
                ('MaChiSo', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã Chỉ Số')),
                ('LoaiDichVu', models.CharField(choices=[('DIEN', 'Điện'), ('NUOC', 'Nước'), ('GAS', 'Gas'), ('KHAC', 'Khác')], default='KHAC', max_length=10, verbose_name='Loại Dịch Vụ')),
                ('Thang', models.IntegerField(verbose_name='Tháng')),
                ('Nam', models.IntegerField(verbose_name='Năm')),
                ('ChiSoCu', models.IntegerField(verbose_name='Chỉ Số Cũ')),
                ('ChiSoMoi', models.IntegerField(verbose_name='Chỉ Số Mới')),
                ('MaCanHo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_so_dien_nuoc', to='apiQuanLy.canho', verbose_name='Mã Căn Hộ')),
            ],
            options={
                'db_table': 'ChiSoDienNuoc',
                'ordering': ['MaChiSo'],
                'constraints': [models.UniqueConstraint(fields=('MaCanHo', 'LoaiDichVu', 'Thang', 'Nam'), name='unique_chi_so_thang_nam')],
            },
        ),
        migrations.AddConstraint(
            model_name='hoadon',
            constraint=models.UniqueConstraint(fields=('MaCanHo', 'Thang', 'Nam'), name='unique_hoa_don_thang_nam'),
        ),
        migrations.AddConstraint(
            model_name='chitiethoadon',
            constraint=models.UniqueConstraint(fields=('MaHoaDon', 'MaLoaiPhi'), name='unique_loai_phi_in_hoa_don'),
        ),
    ]
