# Generated by Django 5.2.8 on 2025-12-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanHo',
            fields=[
                ('MaCanHo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã Căn Hộ')),
                ('SoPhong', models.CharField(max_length=50, unique=True, verbose_name='Số Phòng')),
                ('Tang', models.IntegerField(verbose_name='Tầng')),
                ('ToaNha', models.CharField(max_length=100, verbose_name='Tòa Nhà')),
                ('DienTich', models.FloatField(default=500.0, verbose_name='Diện Tích')),
                ('TrangThai', models.CharField(choices=[('A', 'Trống'), ('B', 'Đã Bán'), ('C', 'Đang Thuê')], max_length=10, verbose_name='Trạng Thái')),
                ('NgayBanGiao', models.DateField(blank=True, null=True, verbose_name='Ngày Bàn Giao')),
            ],
            options={
                'db_table': 'CanHo',
                'ordering': ['MaCanHo'],
            },
        ),
        migrations.CreateModel(
            name='CuDan',
            fields=[
                ('MaCuDan', models.AutoField(help_text='ID TỰ TĂNG (Khóa chính)', primary_key=True, serialize=False, verbose_name='Mã Cư Dân')),
                ('HoTen', models.CharField(max_length=200, verbose_name='Họ và Tên')),
                ('NgaySinh', models.DateField(verbose_name='Ngày Sinh')),
                ('SoCCCD', models.CharField(max_length=20, unique=True, verbose_name='Số CCCD/CMND')),
                ('SoDienThoai', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số Điện Thoại')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('QuanHeVoiChuHo', models.CharField(choices=[('CH', 'Chủ Hộ'), ('VK', 'Vợ/Chồng'), ('CON', 'Con'), ('KHAC', 'Khác')], default='KHAC', max_length=10, verbose_name='Quan Hệ Với Chủ Hộ')),
                ('TrangThaiCuTru', models.CharField(choices=[('TT', 'Tạm Trú'), ('KT', 'Thường Trú')], default='KT', max_length=10, verbose_name='Trạng Thái Cư Trú')),
                ('MaCanHoDangO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chu_can_ho', to='apiQuanLy.canho', verbose_name='Căn Hộ Đang Ở')),
            ],
            options={
                'db_table': 'CuDan',
                'ordering': ['MaCuDan'],
            },
        ),
        migrations.AddField(
            model_name='canho',
            name='MaChuSoHuu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='can_ho_so_huu', to='apiQuanLy.cudan', verbose_name='Chủ Sở Hữu'),
        ),
        migrations.CreateModel(
            name='BienDongDanCu',
            fields=[
                ('MaBienDong', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã Biến Động')),
                ('LoaiBienDong', models.CharField(choices=[('CDI', 'Chuyển đi'), ('CDEN', 'Chuyển đến'), ('TVANG', 'Tạm vắng')], max_length=10, verbose_name='Loại Biến Động')),
                ('NgayBatDau', models.DateField(verbose_name='Ngay Bắt Đầu')),
                ('NgayKetThuc', models.DateField(blank=True, null=True, verbose_name='Ngày Kết Thúc')),
                ('LyDo', models.TextField(blank=True, null=True, verbose_name='Lý Do')),
                ('MaCuDan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_bien_dong', to='apiQuanLy.cudan', verbose_name='Mã Cư Dân')),
            ],
            options={
                'db_table': 'BienDongDanCu',
                'ordering': ['MaBienDong'],
            },
        ),
    ]
