# Generated by Django 5.2.8 on 2025-12-05 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CapNhatHoKhau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoCCCD', models.CharField(max_length=15)),
                ('HoTen', models.CharField(max_length=30)),
                ('Tuoi', models.IntegerField(blank=True, null=True)),
                ('GioiTinh', models.CharField(choices=[('NAM', 'Nam'), ('NU', 'Nữ'), ('KXD', 'Không xác định')], default='NAM', max_length=5)),
                ('SoDT', models.CharField(blank=True, max_length=10, null=True)),
                ('QuanHe', models.CharField(blank=True, max_length=30, null=True)),
                ('TamVang', models.IntegerField(default=0)),
                ('TamTru', models.IntegerField(default=0)),
                ('MaHoKhau', models.ForeignKey(db_column='MaHoKhau', on_delete=django.db.models.deletion.CASCADE, to='CapNhatHoKhau.hokhau')),
            ],
            options={
                'verbose_name_plural': 'Nhân Khẩu',
                'unique_together': {('MaHoKhau', 'SoCCCD')},
            },
        ),
    ]
