CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "password" varchar,
  "email" varchar,
  "role" varchar,
  "cu_dan_id" int,
  "is_active" boolean
);

CREATE TABLE "CanHo" (
  "MaCanHo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaHienThi" varchar UNIQUE,
  "Tang" int,
  "ToaNha" varchar,
  "DienTich" float,
  "MaChuSoHuu" int,
  "TrangThai" varchar
);

CREATE TABLE "CuDan" (
  "MaCuDan" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "HoTen" varchar,
  "NgaySinh" date,
  "SoCCCD" varchar,
  "SoDienThoai" varchar,
  "MaCanHoDangO" int,
  "LaChuHo" boolean,
  "TrangThaiCuTru" varchar
);

CREATE TABLE "BienDongDanCu" (
  "MaBienDong" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaCuDan" int,
  "LoaiBienDong" varchar,
  "NgayThucHien" date
);

CREATE TABLE "DanhMucPhi" (
  "MaLoaiPhi" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TenLoaiPhi" varchar,
  "DonGiaHienTai" decimal,
  "DonViTinh" varchar
);

CREATE TABLE "ChiSoDienNuoc" (
  "MaChiSo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaCanHo" int,
  "LoaiDichVu" varchar,
  "Thang" int,
  "Nam" int,
  "ChiSoCu" int,
  "ChiSoMoi" int,
  "NgayChot" date
);

CREATE TABLE "HoaDon" (
  "MaHoaDon" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaCanHo" int,
  "Thang" int,
  "Nam" int,
  "TongTien" decimal,
  "TrangThai" int,
  "NgayTao" datetime
);

CREATE TABLE "ChiTietHoaDon" (
  "MaChiTiet" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaHoaDon" int,
  "MaLoaiPhi" int,
  "TenPhiSnapshot" varchar,
  "SoLuong" int,
  "DonGiaSnapshot" decimal,
  "ThanhTien" decimal
);

CREATE TABLE "PhuongTien" (
  "MaXe" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaCanHo" int,
  "BienSo" varchar,
  "LoaiXe" varchar
);

CREATE TABLE "YeuCau" (
  "MaYeuCau" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaCuDan" int,
  "TieuDe" varchar,
  "NoiDung" text,
  "TrangThai" varchar,
  "PhanHoiBQL" text,
  "NgayGui" datetime
);

CREATE TABLE "TinTuc" (
  "MaTin" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TieuDe" varchar,
  "NoiDung" text,
  "NguoiDang" int,
  "NgayDang" datetime
);

COMMENT ON COLUMN "Users"."role" IS 'ADMIN, QUAN_LY, CU_DAN';

COMMENT ON COLUMN "Users"."cu_dan_id" IS 'Link nếu user là cư dân';

COMMENT ON COLUMN "CanHo"."MaHienThi" IS 'A-101, B-205...';

COMMENT ON COLUMN "CanHo"."TrangThai" IS 'Trong, DaBan, ChoThue';

COMMENT ON COLUMN "CuDan"."TrangThaiCuTru" IS 'ThuongTru, TamTru';

COMMENT ON COLUMN "BienDongDanCu"."LoaiBienDong" IS 'NhapKhau, ChuyenDi...';

COMMENT ON COLUMN "HoaDon"."TrangThai" IS '0: ChuaThu, 1: DaThu';

COMMENT ON COLUMN "ChiTietHoaDon"."TenPhiSnapshot" IS 'Lưu cứng tên phí lúc tạo';

COMMENT ON COLUMN "ChiTietHoaDon"."DonGiaSnapshot" IS 'Lưu cứng giá lúc tạo';

COMMENT ON COLUMN "YeuCau"."TrangThai" IS 'Moi, DangXuLy, HoanThanh';

ALTER TABLE "Users" ADD FOREIGN KEY ("cu_dan_id") REFERENCES "CuDan" ("MaCuDan");

ALTER TABLE "CanHo" ADD FOREIGN KEY ("MaChuSoHuu") REFERENCES "CuDan" ("MaCuDan");

ALTER TABLE "CuDan" ADD FOREIGN KEY ("MaCanHoDangO") REFERENCES "CanHo" ("MaCanHo");

ALTER TABLE "BienDongDanCu" ADD FOREIGN KEY ("MaCuDan") REFERENCES "CuDan" ("MaCuDan");

ALTER TABLE "ChiSoDienNuoc" ADD FOREIGN KEY ("MaCanHo") REFERENCES "CanHo" ("MaCanHo");

ALTER TABLE "HoaDon" ADD FOREIGN KEY ("MaCanHo") REFERENCES "CanHo" ("MaCanHo");

ALTER TABLE "ChiTietHoaDon" ADD FOREIGN KEY ("MaHoaDon") REFERENCES "HoaDon" ("MaHoaDon");

ALTER TABLE "ChiTietHoaDon" ADD FOREIGN KEY ("MaLoaiPhi") REFERENCES "DanhMucPhi" ("MaLoaiPhi");

ALTER TABLE "PhuongTien" ADD FOREIGN KEY ("MaCanHo") REFERENCES "CanHo" ("MaCanHo");

ALTER TABLE "YeuCau" ADD FOREIGN KEY ("MaCuDan") REFERENCES "CuDan" ("MaCuDan");

ALTER TABLE "TinTuc" ADD FOREIGN KEY ("NguoiDang") REFERENCES "Users" ("id");
