# Generated by Django 5.2.8 on 2025-12-23 18:16

import datetime
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('ma_dich_vu', models.AutoField(primary_key=True, serialize=False)),
                ('ten_dich_vu', models.CharField(max_length=200)),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=12)),
                ('don_vi_tinh', models.CharField(max_length=50)),
                ('loai_dich_vu', models.CharField(choices=[('CO_DINH', 'Phí cố định'), ('BIEN_DOI', 'Phí biến đổi')], default='CO_DINH', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDichVu',
            fields=[
                ('ma_dich_vu', models.IntegerField(blank=True, db_index=True)),
                ('ten_dich_vu', models.CharField(max_length=200)),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=12)),
                ('don_vi_tinh', models.CharField(max_length=50)),
                ('loai_dich_vu', models.CharField(choices=[('CO_DINH', 'Phí cố định'), ('BIEN_DOI', 'Phí biến đổi')], default='CO_DINH', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical dich vu',
                'verbose_name_plural': 'historical dich vus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPhuongTien',
            fields=[
                ('ma_xe', models.IntegerField(blank=True, db_index=True)),
                ('bien_so', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('loai_xe', models.CharField(choices=[('C', 'Ô tô'), ('M', 'Xe máy'), ('B', 'Xe đạp'), ('O', 'Khác')], max_length=50)),
                ('ngay_dang_ky', models.DateField(default=datetime.date.today)),
                ('dang_hoat_dong', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical phuong tien',
                'verbose_name_plural': 'historical phuong tiens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTinTuc',
            fields=[
                ('ma_tin', models.IntegerField(blank=True, db_index=True)),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('ngay_dang', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical tin tuc',
                'verbose_name_plural': 'historical tin tucs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalYeuCau',
            fields=[
                ('ma_yeu_cau', models.IntegerField(blank=True, db_index=True)),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('trang_thai', models.CharField(choices=[('W', 'Chờ Xử Lý'), ('P', 'Đang Xử Lý'), ('A', 'Đã Xử Lý'), ('C', 'Đã Hủy')], default='W', max_length=50)),
                ('phan_hoi_bql', models.TextField(blank=True, null=True)),
                ('ngay_gui', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical yeu cau',
                'verbose_name_plural': 'historical yeu caus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PhuongTien',
            fields=[
                ('ma_xe', models.AutoField(primary_key=True, serialize=False)),
                ('bien_so', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('loai_xe', models.CharField(choices=[('C', 'Ô tô'), ('M', 'Xe máy'), ('B', 'Xe đạp'), ('O', 'Khác')], max_length=50)),
                ('ngay_dang_ky', models.DateField(default=datetime.date.today)),
                ('dang_hoat_dong', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('ma_tin', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YeuCau',
            fields=[
                ('ma_yeu_cau', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('trang_thai', models.CharField(choices=[('W', 'Chờ Xử Lý'), ('P', 'Đang Xử Lý'), ('A', 'Đã Xử Lý'), ('C', 'Đã Hủy')], default='W', max_length=50)),
                ('phan_hoi_bql', models.TextField(blank=True, null=True)),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChiSoDienNuoc',
            fields=[
                ('ma_chi_so', models.AutoField(primary_key=True, serialize=False)),
                ('loai_dich_vu', models.CharField(choices=[('E', 'Điện'), ('W', 'Nước')], max_length=20)),
                ('thang', models.IntegerField()),
                ('nam', models.IntegerField()),
                ('chi_so_cu', models.IntegerField()),
                ('chi_so_moi', models.IntegerField()),
                ('ngay_chot', models.DateField()),
                ('can_ho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_so_dien_nuoc', to='residents.canho')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalChiSoDienNuoc',
            fields=[
                ('ma_chi_so', models.IntegerField(blank=True, db_index=True)),
                ('loai_dich_vu', models.CharField(choices=[('E', 'Điện'), ('W', 'Nước')], max_length=20)),
                ('thang', models.IntegerField()),
                ('nam', models.IntegerField()),
                ('chi_so_cu', models.IntegerField()),
                ('chi_so_moi', models.IntegerField()),
                ('ngay_chot', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('can_ho', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residents.canho')),
            ],
            options={
                'verbose_name': 'historical chi so dien nuoc',
                'verbose_name_plural': 'historical chi so dien nuocs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
