# Generated by Django 5.2.8 on 2025-12-23 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('ma_tin', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YeuCau',
            fields=[
                ('ma_yeu_cau', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('trang_thai', models.CharField(default='ChoXuLy', max_length=50)),
                ('phan_hoi_bql', models.TextField(blank=True, null=True)),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChiSoDienNuoc',
            fields=[
                ('ma_chi_so', models.AutoField(primary_key=True, serialize=False)),
                ('loai_dich_vu', models.CharField(max_length=20)),
                ('thang', models.IntegerField()),
                ('nam', models.IntegerField()),
                ('chi_so_cu', models.IntegerField()),
                ('chi_so_moi', models.IntegerField()),
                ('ngay_chot', models.DateField()),
                ('can_ho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_so_dien_nuoc', to='residents.canho')),
            ],
        ),
        migrations.CreateModel(
            name='PhuongTien',
            fields=[
                ('ma_xe', models.AutoField(primary_key=True, serialize=False)),
                ('bien_so', models.CharField(max_length=20, unique=True)),
                ('loai_xe', models.CharField(max_length=50)),
                ('can_ho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phuong_tien', to='residents.canho')),
            ],
        ),
    ]
