# Generated by Django 5.2.8 on 2025-12-22 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0002_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tintuc',
            name='nguoi_dang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yeucau',
            name='cu_dan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeu_cau', to='residents.cudan'),
        ),
    ]
