# Generated by Django 5.2.8 on 2025-12-24 11:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('ma_dich_vu', models.AutoField(primary_key=True, serialize=False)),
                ('ten_dich_vu', models.CharField(max_length=200)),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=12)),
                ('don_vi_tinh', models.CharField(max_length=50)),
                ('loai_dich_vu', models.CharField(choices=[('CO_DINH', 'Phí cố định'), ('BIEN_DOI', 'Phí biến đổi')], default='CO_DINH', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDichVu',
            fields=[
                ('ma_dich_vu', models.IntegerField(blank=True, db_index=True)),
                ('ten_dich_vu', models.CharField(max_length=200)),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=12)),
                ('don_vi_tinh', models.CharField(max_length=50)),
                ('loai_dich_vu', models.CharField(choices=[('CO_DINH', 'Phí cố định'), ('BIEN_DOI', 'Phí biến đổi')], default='CO_DINH', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical dich vu',
                'verbose_name_plural': 'historical dich vus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
