# Generated by Django 5.2.8 on 2025-12-05 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoKhau',
            fields=[
                ('MaHoKhau', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DiaChi', models.CharField(max_length=30)),
                ('NgayLap', models.DateField(default=datetime.date.today)),
                ('NgayChuyenDi', models.DateField(blank=True, null=True)),
                ('LyDoChuyenDi', models.CharField(blank=True, max_length=255, null=True)),
                ('DienTichHo', models.FloatField(default=0.0)),
                ('SoXeMay', models.IntegerField(default=0)),
                ('SoOto', models.IntegerField(default=0)),
                ('SoXeDap', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Hộ Khẩu',
            },
        ),
    ]
