# Generated by Django 5.2.8 on 2025-12-23 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucPhi',
            fields=[
                ('ma_loai_phi', models.AutoField(primary_key=True, serialize=False)),
                ('ten_loai_phi', models.CharField(max_length=100)),
                ('dong_gia_hien_tai', models.DecimalField(decimal_places=2, max_digits=10)),
                ('don_vi_tinh', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('ma_hoa_don', models.AutoField(primary_key=True, serialize=False)),
                ('thang', models.IntegerField()),
                ('nam', models.IntegerField()),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trang_thai', models.IntegerField(default=0)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('ma_chi_tiet', models.AutoField(primary_key=True, serialize=False)),
                ('ten_phi_snapshot', models.CharField(max_length=100)),
                ('so_luong', models.IntegerField()),
                ('dong_gia_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loai_phi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.danhmucphi')),
            ],
        ),
    ]
