# Generated by Django 5.2.8 on 2025-12-23 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='can_ho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don', to='residents.canho'),
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='hoa_don',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='finance.hoadon'),
        ),
    ]
