# Generated by Django 5.2.8 on 2025-12-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='ngay_thanh_toan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
