# Generated by Django 5.2.8 on 2025-12-27 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_hoadon_ngay_thanh_toan'),
        ('residents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotDongGop',
            fields=[
                ('ma_dot', models.AutoField(primary_key=True, serialize=False)),
                ('ten_dot', models.CharField(max_length=200)),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DongGop',
            fields=[
                ('ma_dong_gop', models.AutoField(primary_key=True, serialize=False)),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ngay_dong', models.DateTimeField(auto_now_add=True)),
                ('hinh_thuc', models.CharField(choices=[('TM', 'Tiền mặt'), ('CK', 'Chuyển khoản')], default='TM', max_length=2)),
                ('can_ho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_dong_gop', to='residents.canho')),
                ('dot_dong_gop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_dong_gop', to='finance.dotdonggop')),
            ],
        ),
    ]
