# Generated by Django 5.2.8 on 2025-12-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_dotdonggop_donggop'),
    ]

    operations = [
        migrations.AddField(
            model_name='donggop',
            name='trang_thai',
            field=models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('TU_CHOI', 'Từ chối')], default='CHO_DUYET', max_length=20),
        ),
    ]
