# Generated by Django 5.2.8 on 2025-12-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_donggop_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donggop',
            name='trang_thai',
            field=models.CharField(choices=[('CHO_XAC_NHAN', 'Chờ xác nhận'), ('DA_DONG_GOP', 'Đã đóng góp'), ('TU_CHOI', 'Từ chối')], default='CHO_XAC_NHAN', max_length=20),
        ),
    ]
