# Generated by Django 5.2.8 on 2025-12-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_donggop_trang_thai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danhmucphi',
            old_name='ma_loai_phi',
            new_name='ma_phi',
        ),
        migrations.RenameField(
            model_name='danhmucphi',
            old_name='ten_loai_phi',
            new_name='ten_phi',
        ),
        migrations.RemoveField(
            model_name='danhmucphi',
            name='dong_gia_hien_tai',
        ),
        migrations.AddField(
            model_name='danhmucphi',
            name='don_gia',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='danhmucphi',
            name='loai_phi',
            field=models.CharField(default='', max_length=50),
        ),
    ]
