# Generated by Django 5.2.8 on 2025-12-23 18:16

import datetime
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanHo',
            fields=[
                ('ma_can_ho', models.AutoField(primary_key=True, serialize=False)),
                ('phong', models.CharField(max_length=20)),
                ('tang', models.IntegerField()),
                ('toa_nha', models.CharField(max_length=50)),
                ('dien_tich', models.FloatField(default=500.0)),
                ('trang_thai', models.CharField(choices=[('E', 'Trống'), ('S', 'Đã bán'), ('H', 'Đang thuê')], default='E', max_length=50)),
            ],
            options={
                'db_table': 'CanHo',
                'ordering': ['ma_can_ho'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCanHo',
            fields=[
                ('ma_can_ho', models.IntegerField(blank=True, db_index=True)),
                ('phong', models.CharField(max_length=20)),
                ('tang', models.IntegerField()),
                ('toa_nha', models.CharField(max_length=50)),
                ('dien_tich', models.FloatField(default=500.0)),
                ('trang_thai', models.CharField(choices=[('E', 'Trống'), ('S', 'Đã bán'), ('H', 'Đang thuê')], default='E', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical can ho',
                'verbose_name_plural': 'historical can hos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCuDan',
            fields=[
                ('ma_cu_dan', models.IntegerField(blank=True, db_index=True)),
                ('ho_ten', models.CharField(max_length=100)),
                ('gioi_tinh', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=10)),
                ('ngay_sinh', models.DateField()),
                ('so_cccd', models.CharField(db_index=True, max_length=20)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('la_chu_ho', models.BooleanField(default=False)),
                ('trang_thai_cu_tru', models.CharField(choices=[('TT', 'Tạm Trú'), ('TH', 'Thường Trú'), ('TV', 'Tạm Vắng'), ('OUT', 'Đã Chuyển Đi')], default='TT', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical cu dan',
                'verbose_name_plural': 'historical cu dans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CuDan',
            fields=[
                ('ma_cu_dan', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
                ('gioi_tinh', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=10)),
                ('ngay_sinh', models.DateField()),
                ('so_cccd', models.CharField(max_length=20, unique=True)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('la_chu_ho', models.BooleanField(default=False)),
                ('trang_thai_cu_tru', models.CharField(choices=[('TT', 'Tạm Trú'), ('TH', 'Thường Trú'), ('TV', 'Tạm Vắng'), ('OUT', 'Đã Chuyển Đi')], default='TT', max_length=50)),
                ('can_ho_dang_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cu_dan_hien_tai', to='residents.canho')),
            ],
            options={
                'db_table': 'CuDan',
                'ordering': ['ma_cu_dan'],
            },
        ),
        migrations.AddField(
            model_name='canho',
            name='chu_so_huu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_huu_can_ho', to='residents.cudan'),
        ),
        migrations.CreateModel(
            name='BienDongDanCu',
            fields=[
                ('ma_bien_dong', models.AutoField(primary_key=True, serialize=False)),
                ('loai_bien_dong', models.CharField(choices=[('TH', 'Thường trú'), ('TT', 'Tạm trú'), ('TV', 'Tạm Vắng'), ('OUT', 'Chuyển Đi')], max_length=50)),
                ('ngay_thuc_hien', models.DateField(default=datetime.date.today)),
                ('can_ho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bien_dong_can_ho', to='residents.canho')),
                ('cu_dan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bien_dong_cu_dan', to='residents.cudan')),
            ],
            options={
                'db_table': 'BienDongDanCu',
                'ordering': ['ma_bien_dong'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBienDongDanCu',
            fields=[
                ('ma_bien_dong', models.IntegerField(blank=True, db_index=True)),
                ('loai_bien_dong', models.CharField(choices=[('TH', 'Thường trú'), ('TT', 'Tạm trú'), ('TV', 'Tạm Vắng'), ('OUT', 'Chuyển Đi')], max_length=50)),
                ('ngay_thuc_hien', models.DateField(default=datetime.date.today)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('can_ho', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residents.canho')),
                ('cu_dan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residents.cudan')),
            ],
            options={
                'verbose_name': 'historical bien dong dan cu',
                'verbose_name_plural': 'historical bien dong dan cus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
