# Generated by Django 5.2.8 on 2025-12-18 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanHo',
            fields=[
                ('ma_can_ho', models.AutoField(primary_key=True, serialize=False)),
                ('ma_hien_thi', models.CharField(max_length=20, unique=True)),
                ('tang', models.IntegerField()),
                ('toa_nha', models.CharField(max_length=50)),
                ('dien_tich', models.FloatField()),
                ('trang_thai', models.CharField(default='Trong', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CuDan',
            fields=[
                ('ma_cu_dan', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('so_cccd', models.CharField(max_length=20, unique=True)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('la_chu_ho', models.BooleanField(default=False)),
                ('trang_thai_cu_tru', models.CharField(default='TamTru', max_length=50)),
                ('can_ho_dang_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cu_dan_hien_tai', to='residents.canho')),
            ],
        ),
        migrations.CreateModel(
            name='BienDongDanCu',
            fields=[
                ('ma_bien_dong', models.AutoField(primary_key=True, serialize=False)),
                ('loai_bien_dong', models.CharField(max_length=50)),
                ('ngay_thuc_hien', models.DateField()),
                ('cu_dan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bien_dong', to='residents.cudan')),
            ],
        ),
    ]
