# Generated by Django 5.2.8 on 2025-12-21 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biendongdancu',
            name='can_ho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_su_bien_dong', to='residents.canho'),
        ),
    ]
